name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: macos-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.3"

      - name: Install dependencies
        run: |
          npm install

      - name: Start the server
        run: |
          npm start &
        env:
          CYPRESS_baseUrl: "http://localhost:8080/parabank/index.htm"

      - name: Run Cypress tests
        run: |
          npx cypress run cypress.config.js
        env:
          CI: true
