name: Tomcat Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tomcat:
    runs-on: windows-latest # check if it runs on windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -R

      - name: Create logs directory
        run: mkdir -p tools/apache-tomcat-10.1.29/logs_win # changed path because this already exists

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Start Tomcat
        run: |
          cd tools/apache-tomcat-10.1.29/bin
          nohup ./startup.sh > ../logs/catalina.out 2>&1 &
          sleep 30

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('ParaBank/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: npm install

      - name: Run Cypress install
        run: npx cypress install

      - name: Run Cypress tests
        run: npx cypress run
        base_url: "http://localhost:8080/parabank/index.htm"

      - name: Stop Tomcat
        run: |
          cd tools/apache-tomcat-10.1.29/bin
          ./shutdown.sh
