name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: macos-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Java (for Tomcat)
        uses: actions/setup-java@v3
        with:
          java-version: "17"

      - name: Install dependencies
        run: npm install

      - name: Start Tomcat
        run: |
          cd /Users/bartek/Desktop/Parabank-task/apache-tomcat-10.1.29/bin/
          ./startup.sh & 
          # Wait for Tomcat to start
          sleep 30

      - name: Run Cypress tests
        run: |
          npx cypress run
        env:
          CI: true
